sync:
  build: ./user-service
  ports:
   - "8082:8082"
  volumes:
   - ./user-service:/src
  links:
   - rabbit
  command: node index.js
rabbit:
  image: rabbitmq:3.5.6-management
  ports:
   - "8083:15672"
