rabbit:
  image: rabbitmq:3.5.6-management
  ports:
   - "9091:15672"
user-service:
  build: ./user-service
  ports:
   - "8082:8082"
  volumes:
   - ./user-service:/src
  links:
   - rabbit
  command: ./start.sh
reward-service:
  build: ./reward-service
  ports:
   - "8083:8083"
  volumes:
   - ./reward-service:/src
  links:
   - rabbit
#  command: node index.js
